# Generated by Django 2.1.4 on 2018-12-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactor',
            name='username',
            field=models.CharField(default='', max_length=70),
        ),
    ]
